version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
<<<<<<< HEAD
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build
=======
>>>>>>> aac1396 (update config.yml)

jobs:
  build:
    working_directory: ~/ExampleApplication
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
<<<<<<< HEAD
          name: install-npm-wee
          command: npm install
=======
          name: install-npm
          command: npm install
      - run:
          name: test-run
          command: npm run test
>>>>>>> aac1396 (update config.yml)
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
<<<<<<< HEAD
  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf ExampleApplication/; git clone https://github.com/artofgraham/ExampleApplication.git; source ExampleApplication/deploy.sh"
=======
>>>>>>> aac1396 (update config.yml)
